language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
script: ./gradlew shadowJar
deploy:
  provider: releases
  api_key:
    secure: i3hNzRcz3j1bD2LgjG5/B/NWvL5yekWHbkbe4WPTBR93uqLIMrd/4+5LLM0sl1h8hvXy/wvTshGlgX8Q0PhZwwBBkf5gmqYH5MjF49F1zB7L7vE391nkvAYymVvyh+gzZ8f5Xc6GbH3p/7S+rzCg1jkbLfycZW2JsMoAzGQilmoKbmN+48qLU87Dxe/PSEzPk1R00B+mq3y35jlxqEYNE7DYtEdZdxRcfJCvhNxGFuvur2aTYetV4u3sfy0fnBra0VuBzpadk97kB0vAdVdB6iRlMFJu8uuIm9+JKAiwLzwXOnZmdUjEUOwJA3m+vmVwsslBTHBFjpieMcNupmEfRVA7jCctJGLsWFAgbP/apoH0xe3D3TgsFtof4WhdLisWw4oaMmZGTTE/PRc2VaSuh6whKhZzevTroyuApHfzOd6a2HL7jTP+rTSCa09Yj9O57dJXn7nOHAE9bVjjXpsb9Gjr1ggEYrhAP7OHJIl7LDSchUhKItoewmOHBoa2CD7e6UXhRneArs934e4WQ+00aBDpvtNctxM4LRop88vfvfOy3K0iPZ8LxZg7Avr2W6Z2dTCai/ahlO/3NBGVOCtpxgw+B7Aa6MHHSYuYY0EqC32Ur/kAGX12f6tY7GPmOK5ARtA/d5mUndC2gijFFiLISN0ZiTWnCQs9wXNC/O9ouSo=
  file: build/libs/MazeStuff-1.0-SNAPSHOT-all.jar
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: CdGsAr8JnPOj2sKdbTuHunWIOEHb27myvzVpNTeTvd0rVxD5Wq4X2Lns0X31Zh1aXNMIXslV9BdSdy+K9fsie5+98zU24xMYweIoDGvi3ciIVNPA/hZe1ZgMapKVchn91PxFKuzxz1SnkeytKA7vwxdiVzJEPDCx2G3PQWtxxCNql/ndJdLb8WsiyFYQt1f/uURazJa2lqsjr09F7Xzmu6gu8qACSRfzx7ICAZVMCbAkOMbq//IbQcszQoyE7W2G/+GxeXRZMX6S9yRQbaa8mBGn4fTvYhd+hDqvRAPM2VBGy4BPL258KVfYlx43rZ+SWwEBqCQdBOU3HykGhzBrEhwWR9pelIqf7/5Gn0wLxYMEt3STdZssJbzuYFVlZXDGeI/K5eVRFhXXpRwwAt+Ab5oaDIGpWNIOV3hfoCVCBNkIJMwyamOBomjHAQnF6edxvmG6jJvTtQWSR8fjgLD0LReasSZXr8aq+7PzDFOeZqWzSYXTPfsdVKs9n8U2bAVa9DrMObmZ+bJaA3gfwZLOHTqPrYp+JJqeEQEsngw/KJ4VyY0pj09UoJo/WejD56teeXyTNIG4pt0sbofgzWU6xK1QHZp+gMent4qysm/3finYJQzwpLnKGUjLp8boE8PSNv/vru+g2bsZSLvhFMjd9AcDYl6futUdDmZourj1RhY=